import { Product } from "./types";

export const products: Product[] = [
    {
        id:1,
        title: "Long Shoes Accessories",
        image: ["/1/m-7.jpg","/1/m-6.jpg"],
        slug: "long-shoes-accessories",
        price: 250,
        discount:3,
        category: "shoes",
        description:" Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.",
        size: ['S','M','L','XL'],
        color: ["#ffffff", "#000000", "#FCA966"],
        qty:2,

    },
    {
        id:2,
        title: "Women long Top",
        image: ["/1/m-6.jpg","/1/m-6.jpg"],
        slug: "women-long-top",
        price: 150,
        discount:3,
        category: "tops",
        description:" Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.",
        size: ['S','M','L','XL'],
        color: ["#ffffff", "#000000", "#FCA966"],
        qty:1,
    },
    {
        id:3,
        title: "Brown Jacket",
        image: ["/1/m-3.jpg","/1/m-3.jpg"],
        slug: "lather-brown-jacket",
        price: 150,
        discount:0,
        category: "tops",
        description:" Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.",
        size: ['S','M','L','XL'],
        color: ["#ffffff", "#000000", "#asiwe0"],
        qty:1,
    },
    {
        id:4,
        title: "Women Long Coat",
        image: ["/1/g-4.jpg","/1/g-4.jpg"],
        slug: "women-long-coat",
        price: 350,
        discount:7,
        category: "accessories",
        description:" Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.",
        size: ['S','M','L','XL'],
        color: ["#ffffff", "#000000", "#asfsf0"],
        qty:1,
    },
    {
        id:5,
        title: "Cold Wether Women Coat",
        image: ["/1/g-3.jpg","/1/g-3.jpg"],
        slug: "cold-wether-women-coat",
        price: 250,
        discount:2,
        category: "tops",
        description:" Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.",
        size: ['S','M','L','XL'],
        color: ["#ffffff", "#000000", "#FCA966"],
        qty:2,
    },
    {
        id:6,
        title: "Black Denim Printed Tee",
        image: ["/1/g-8.jpg","/1/g-8.jpg"],
        slug: "black-denim-printed-tee",
        price: 800,
        discount:50,
        category: "pants",
        description:" Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.",
        size: ['S','M','L','XL'],
        color: ["#ffffff", "#000000", "#000000"],
        qty:1,
    },
    {
        id:7,
        title: "Long Shoes Accessories",
        image: ["/1/m-7.jpg","/1/m-7.jpg"],
        slug: "long-shoes-accessories",
        price: 250,
        discount:3,
        category: "shoes",
        description:" Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.",
        size: ['S','M','L','XL'],
        color: ["#ffffff", "#000000", "#FCA966"],
        qty:2,
    },
    {
        id:8,
        title: "Women long Top",
        image: ["/1/m-6.jpg","/1/m-6.jpg"],
        slug: "women-long-top",
        price: 150,
        discount:3,
        category: "tops",
        description:" Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.",
        size: ['S','M','L','XL'],
        color: ["#ffffff", "#000000", "#FCA966"],
        qty:1,
    },
    {
        id:9,
        title: "Brown Jacket",
        image: ["/1/m-3.jpg","/1/m-3.jpg"],
        slug: "lather-brown-jacket",
        price: 150,
        discount:0,
        category: "tops",
        description:" Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.",
        size: ['S','M','L','XL'],
        color: ["#ffffff", "#000000", "#asiwe0"],
        qty:1,
    },
    {
        id:10,
        title: "Women Long Coat",
        image: ["/1/g-4.jpg","/1/g-4.jpg"],
        slug: "women-long-coat",
        price: 350,
        discount:7,
        category: "accessories",
        description:" Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.",
        size: ['S','M','L','XL'],
        color: ["#ffffff", "#000000", "#asfsf0"],
        qty:1,
    },
    {
        id:11,
        title: "Cold Wether Women Coat",
        image: ["/1/g-3.jpg","/1/g-3.jpg"],
        slug: "cold-wether-women-coat",
        price: 250,
        discount:2,
        category: "tops",
        description:" Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.",
        size: ['S','M','L','XL'],
        color: ["#ffffff", "#000000", "#FCA966"],
        qty:2,
    },
    {
        id:12,
        title: "Black Denim Printed Tee",
        image: ["/1/g-8.jpg","/1/g-8.jpg"],
        slug: "black-denim-printed-tee",
        price: 800,
        discount:50,
        category: "pants",
        description:" Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.Best Quality tshirt for women.",
        size: ['S','M','L','XL'],
        color: ["#ffffff", "#000000", "#000000"],
        qty:1,
    },
]